version: '3.8'

services:
  backend:
    build: ./Backend
    image: projectpilot-backend:1.0
    container_name: project_pilot_backend
    ports:
      - "5000:5000" # Maps host 5000 to container 5000
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb+srv://npushkar0411:h59lYh5DUsMU8taB@pilotcluster0.cxmpwc6.mongodb.net/ProjectPilot
      - SECRET_KEY=your_secret_key
      - JWT_SECRET=donewithlife
      - FRONT_BASE=http://localhost:3000
      - TWILO_SAFE_CODE=RHC4XBWQXC1658W7HDTSPTHH
      - TWILIO_ACCOUNT_SID=VAd37c78101c42438cb013a242fc9e2704
      - ORG_NM=Syspro Infotech Pvt. Ltd.
      - MAIL_ID=project.piloteg@gmail.com
      - MAIL_PASS=xiojrimfoynkeakd

    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_BASE_URL=http://localhost:5000/api/v1
    image: projectpilot-frontend:v2-dev
    container_name: project_pilot_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
